### ISSUE TITLE
Closing websocket client

### ISSUE THREAD

**Issue by tikheshaileshn** [andyglow/websocket-scala-client#3]
**Issue: calling cli.shutdown closes websocket incorrectly.**
```
val cli = WebsocketClient(Uri(apiUrl), protocolHandler, headers)
val ws = cli.open()
// SOME CODE
cli.shutdown()
```

When cli.shutdown is called, I see following errors at server: 

```
java.nio.channels.ClosedChannelException
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:128)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:99)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
        at org.jboss.netty.channel.Channels.write(Channels.java:725)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
        at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292)
        at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254)
        at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.handleDownstream(HttpPipeliningHandler.java:106)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
        at org.jboss.netty.channel.Channels.write(Channels.java:704)
        at org.jboss.netty.channel.Channels.write(Channels.java:671)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:348)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$play$core$server$netty$PlayDefaultUpstreamHandler$$iteratee$1$1.apply(PlayDefaultUpstreamHandler.scala:298)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$play$core$server$netty$PlayDefaultUpstreamHandler$$iteratee$1$1.apply(PlayDefaultUpstreamHandler.scala:291)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$16$$anonfun$apply$17.apply(Iteratee.scala:544)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$16$$anonfun$apply$17.apply(Iteratee.scala:544)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109)
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71)
        at scala.concurrent.impl.Future$.apply(Future.scala:31)
        at scala.concurrent.Future$.apply(Future.scala:494)
        at play.api.libs.iteratee.RunQueue.execute(RunQueue.scala:122)
        at play.api.libs.iteratee.RunQueue.schedule(RunQueue.scala:115)
        at play.api.libs.iteratee.RunQueue.schedule(RunQueue.scala:66)
        at play.api.libs.iteratee.RunQueue.scheduleSimple(RunQueue.scala:88)
        at play.api.libs.iteratee.Concurrent$$anon$10$$anon$11.schedule(Concurrent.scala:459)
        at play.api.libs.iteratee.Concurrent$$anon$10$$anon$11.push(Concurrent.scala:484)
        at play.api.libs.iteratee.Concurrent$Channel$class.push(Concurrent.scala:50)
        at play.api.libs.iteratee.Concurrent$$anon$10$$anon$11.push(Concurrent.scala:456)
        at managers.DeviceActorWS$$anonfun$receive$3.applyOrElse(Relay2.scala:332)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
        at managers.DeviceActorWS.aroundReceive(Relay2.scala:224)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

How can I disconnect websocket client gracefully so that I don't get such error stack at server side?
I am connecting this websocket client to play application.

**Comment by andyglow** [comment]
The reason you can see that error is the fact you still send the data after you close the connection.
You still have to call `ws.close()` before you call `cli.shutdown()`

**Comment by tikheshaileshn** [comment]
```
val protocolHandler = new WebsocketHandler[String]() {
  def receive = {
    case str =>
      println(s"received message: $str")
      Thread.sleep(3000)
      sender() ! "<heartbeat>true</heartbeat>"
  }
}

def main(args: Array[String]): Unit = {
  val headers = getRequestHeaders
  val apiUrl = """10.70.70.123/websocket"""
  val cli = WebsocketClient(Uri(apiUrl), protocolHandler, headers)
  val ws = cli.open()
  Thread.sleep(1 * 100 * 1000)
  ws.close()
  cli.shutdown()
}

def getRequestHeaders: Map[String, String] =  {
  val config = ConfigFactory.load
  val headerKeys = Seq("token", "username", "password")
  Map(headerKeys.map(h => h -> config.getString(h)): _*)
}
```
Thank you for your suggestions, I was closing ws after shutting cli down. Above is my current implementation.
I tried **ws.close()**, but still I can see channel closed exception at server side.
I don't get any error at client. What is graceful way to tell server to close connection?
Is there any way to close websocket connection inside handler?

**Comment by andyglow** [comment]
I jave just tried it on play app. The code is here https://gist.github.com/andyglow/0aeb4c47fe2f0bc058147d6765995c3c

And I haven't manage to get the same errors.
Server Output for `SimplifiedTextEchoWebSocketOrg` example was:
```
accepting GET /ws-echo
starting
>> hello
<< hello
>> world
<< world
>> stop
<< stop
stopped
```
while client output was
```
[nioEventLoopGroup-2-1] INFO echo-websocket-example - <<| hello
[nioEventLoopGroup-2-1] INFO echo-websocket-example - <<| world
[nioEventLoopGroup-2-1] INFO echo-websocket-example - <<! stop
[ForkJoinPool-1-worker-11] INFO echo-websocket-example - !!! [closed]
```

Can you may be show me the way you use websocket at server side?

**Comment by andyglow** [comment]
Also please try `0.2.1` version

**Comment by tikheshaileshn** [comment]
I found that problem was with my client code.

```
scala> ws.close
res4: scala.concurrent.Future[Unit] = Success(())
```

My code was:

```
def main(args: Array[String]): Unit = {
  val headers = getRequestHeaders
  val apiUrl = """10.70.70.123/websocket"""
  val cli = WebsocketClient(Uri(apiUrl), protocolHandler, headers)
  val ws = cli.open()
  Thread.sleep(1 * 100 * 1000)
  ws.close()
  cli.shutdown()
}
```

As ws.close is asynchronous, my program was getting terminated before ws.close Future gets completed.  This caused server to print erros. 
BTW, your library is awesome. It helped me a lot, I have written everything for my load-test but couldn't write websocket client in scala. This helped me very very much! :+1:

**Comment by andyglow** [comment]
You're welcome!
